FROM mmseqsweb_mmseqs-web-mmseqs

RUN apt-get update \
    && apt-get -y --no-install-recommends install pigz \ 
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

ADD . /var/www/mmseqs-web
RUN cd /var/www/mmseqs-web && composer install

RUN usermod -u 1000 www-data
USER www-data

WORKDIR "/var/www/mmseqs-web"

CMD ["/usr/bin/php", "/var/www/mmseqs-web/worker.php"]
