#!/usr/bin/env node
// Bundle the server and core into one file, so the published package needs only the MCP SDK.
//
// core cannot be published on its own: it imports frontend/lib by relative path, which is outside its
// package. Inlining is what makes that graph shippable.

import { build } from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'dist', 'server.mjs');

const result = await build({
    entryPoints: [path.join(HERE, 'src', 'server.js')],
    outfile: OUT,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    external: ['@modelcontextprotocol/sdk/*'],
    banner: { js: '// Generated by build.mjs — do not edit, do not commit.' },
    metafile: true,
    logLevel: 'warning',
});

const { size } = await fs.stat(OUT);
const externals = [...new Set(Object.values(result.metafile.outputs)
    .flatMap(o => o.imports ?? []).filter(i => i.external).map(i => i.path))];
process.stderr.write(`dist/server.mjs  ${(size / 1024).toFixed(0)} KB  external: ${externals.join(', ')}\n`);
