#!/usr/bin/env node
// Bundle the server and core into one file for release artifacts.
//
// core cannot be distributed on its own: it imports frontend/lib by relative path, which is outside
// its directory, and frontend/lib in turn imports molstar. Inlining is what makes that graph
// portable, and minifying keeps molstar's share of it down.

import { build } from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const OUT = path.join(HERE, 'dist', 'server.mjs');
const MOLSTAR_ESM = path.join(ROOT, 'frontend', 'lib', 'node_modules', 'molstar', 'lib');

const result = await build({
    absWorkingDir: HERE,
    entryPoints: [path.join(HERE, 'src', 'server.js')],
    outfile: OUT,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    minify: true,
    // frontend/lib names molstar's commonjs tree so Node can run it unbundled; esbuild tree-shakes
    // the ESM one far better.
    alias: { 'molstar/lib/commonjs': MOLSTAR_ESM },
    external: ['@modelcontextprotocol/sdk/*'],
    banner: { js: '// Generated by build.mjs — do not edit, do not commit.' },
    metafile: true,
    logLevel: 'warning',
});

const { size } = await fs.stat(OUT);
const externals = [...new Set(Object.values(result.metafile.outputs)
    .flatMap(o => o.imports ?? []).filter(i => i.external).map(i => i.path))];
process.stderr.write(`dist/server.mjs  ${(size / 1024).toFixed(0)} KB  external: ${externals.join(', ')}\n`);
